project_name: ntfyexec
release:
  github:
    owner: alecthomas
    name: ntfyexec
env:
  - CGO_ENABLED=0
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
      - amd64
      - "386"
    goarm:
      - "6"
    dir: .
    main: .
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: ntfyexec
archives:
  - format: tar.gz
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
